
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGDC.Model
{

using System;
    using System.Collections.Generic;
    
public partial class datadictionaryinfo
{

    public int DD_ID { get; set; }

    public string DD_Type { get; set; }

    public string DD_Value { get; set; }

    public string DD_Desc { get; set; }

    public string DD_Ext1 { get; set; }

    public string DD_Ext2 { get; set; }

    public string DD_Ext3 { get; set; }

}

}
