
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGDC.Model
{

using System;
    using System.Collections.Generic;
    
public partial class documentinfo
{

    public int D_ID { get; set; }

    public string D_Type { get; set; }

    public string D_Head { get; set; }

    public string D_Subhead { get; set; }

    public string D_Content { get; set; }

    public System.DateTime D_CreateTime { get; set; }

    public System.DateTime D_UpdateTime { get; set; }

    public string D_Ext1 { get; set; }

    public string D_Ext2 { get; set; }

    public string D_Ext3 { get; set; }

}

}
