//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shiguhouguoinfo
    {
        public int HG_ID { get; set; }
        public int JB_ID { get; set; }
        public string HG_ZD_ShangXing { get; set; }
        public string HG_ZD_XiaXing { get; set; }
        public string HG_DW_ShangXing { get; set; }
        public string HG_DW_XiaXing { get; set; }
        public string HG_TG_DongCheZu { get; set; }
        public string HG_TG_JiChe { get; set; }
        public string HG_TG_KeChe { get; set; }
        public string HG_TG_HuoChe { get; set; }
        public string HG_SS_DongCheZu { get; set; }
        public string HG_SS_JiChe { get; set; }
        public string HG_SS_CheLiang { get; set; }
        public string HG_SS_QiTa { get; set; }
        public string HG_ZhiJieSunShi { get; set; }
        public string HG_XZ_JiDongChe { get; set; }
        public string HG_XZ_FeiJiDongChe { get; set; }
        public string HG_XZ_XingRen { get; set; }
        public string HG_XZ_DaoKouQingKuang { get; set; }
        public string HG_XZ_GongTieBingXing { get; set; }
        public string HG_XZ_FangHuZhaLan { get; set; }
        public string HG_XZ_GongTieLiJiao { get; set; }
        public string HG_XZ_SuDuQuDuan { get; set; }
        public string HG_XZ_QuXianBanJing { get; set; }
        public string HG_XZ_PoDu { get; set; }
        public string HG_SW_XingMing { get; set; }
        public string HG_SW_DanWei { get; set; }
        public string HG_SW_XingBie { get; set; }
        public string HG_SW_NianLing { get; set; }
        public string HG_SW_MinZu { get; set; }
        public string HG_SW_GongZhong { get; set; }
        public string HG_SW_ShangHaiChengDu { get; set; }
        public string HG_SW_RenYuanShuXing { get; set; }
        public string HG_SiW_LuNei { get; set; }
        public string HG_SiW_LuWai { get; set; }
        public string HG_ZS_LuNei { get; set; }
        public string HG_ZS_LuWai { get; set; }
        public string HG_QS_LuNei { get; set; }
        public string HG_QS_LuWai { get; set; }
        public string HG_ShiGuGaiKuang { get; set; }
        public string HG_Ext1 { get; set; }
        public string HG_Ext2 { get; set; }
        public string HG_Ext3 { get; set; }
    }
}
