
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGDC.Model
{

using System;
    using System.Collections.Generic;
    
public partial class shiguzerendanweiinfo
{

    public int ZRDW_ID { get; set; }

    public int JB_ID { get; set; }

    public string ZRDW_DanWei { get; set; }

    public string ZRDW_DanWeiShuXing { get; set; }

    public string ZRDW_BuMen { get; set; }

    public string ZRDW_ChengDu { get; set; }

    public string ZRDW_Ext1 { get; set; }

    public string ZRDW_Ext2 { get; set; }

    public string ZRDW_Ext3 { get; set; }

}

}
