//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shiguzerenrendinginfo
    {
        public int ZR_ID { get; set; }
        public int JB_ID { get; set; }
        public string ZR_ZeRenDanWei { get; set; }
        public string ZR_ZeRenDanWeiShuXing { get; set; }
        public string ZR_ZeRenBuMen { get; set; }
        public string ZR_ZeRenChengDu { get; set; }
        public string ZR_YuanYinLeiBie { get; set; }
        public string ZR_ShiGuLeiBie { get; set; }
        public string ZR_XingChe { get; set; }
        public string ZR_ZhiBanJianCha { get; set; }
        public Nullable<System.DateTime> ZR_TianBaoShiJian { get; set; }
        public string ZR_BaoGaoCiShu { get; set; }
        public string ZR_ShiGuDiaoChaBaoGao { get; set; }
        public string ZR_XianChangDianChaZiLiao { get; set; }
        public string ZR_SunShiJiSuanZiLiao { get; set; }
        public string ZR_ShiGuRenDingShu { get; set; }
        public string ZR_AnJianBaoEr { get; set; }
        public string ZR_QiTa { get; set; }
        public string ZR_TePaiBanDiaoChaBaoGao { get; set; }
        public string ZR_SheDuDiaoChaBaoGao { get; set; }
        public string ZR_Ext1 { get; set; }
        public string ZR_Ext2 { get; set; }
        public string ZR_Ext3 { get; set; }
    }
}
