
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGDC.Model
{

using System;
    using System.Collections.Generic;
    
public partial class shiguzhuantiinfo
{

    public int ZT_ID { get; set; }

    public int JB_ID { get; set; }

    public string ZT_Type { get; set; }

    public string ZT_FilePath { get; set; }

    public string ZT_Desc { get; set; }

    public int ZT_CreateUserID { get; set; }

    public string ZT_CreateUser { get; set; }

    public System.DateTime ZT_CreateTime { get; set; }

    public string ZT_Ext1 { get; set; }

    public string ZT_Ext2 { get; set; }

    public string ZT_Ext3 { get; set; }

}

}
