//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shiguhouguoshangwanginfo
    {
        public int SW_ID { get; set; }
        public int JB_ID { get; set; }
        public string SW_Name { get; set; }
        public string SW_Unit { get; set; }
        public string SW_Sex { get; set; }
        public int SW_Age { get; set; }
        public string SW_MinZu { get; set; }
        public string SW_ShangHaiChengDu { get; set; }
        public string SW_RenYuanShuXing { get; set; }
        public string SW_Ext1 { get; set; }
        public string SW_Ext2 { get; set; }
        public string SW_Ext3 { get; set; }
    }
}
