//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shigujibeninfo
    {
        public int JB_ID { get; set; }
        public string JB_DD_Ju { get; set; }
        public string JB_DD_Xian { get; set; }
        public string JB_DD_XianBie { get; set; }
        public string JB_DD_QiDian { get; set; }
        public string JB_DD_ZhongDian { get; set; }
        public string JB_DD_XingBie { get; set; }
        public string JB_DD_GongLi { get; set; }
        public string JB_DD_MiShu { get; set; }
        public string JB_DD_Sheng { get; set; }
        public string JB_DD_Shi { get; set; }
        public string JB_DD_Qu { get; set; }
        public string JB_DD_DanWei { get; set; }
        public string JB_DD_ChangSuo { get; set; }
        public string JB_LC_CheCi { get; set; }
        public string JB_LC_CheHao { get; set; }
        public string JB_LC_QiDian { get; set; }
        public string JB_LC_ZhongDian { get; set; }
        public string JB_LC_PeiShu { get; set; }
        public string JB_LC_DanDang { get; set; }
        public string JB_LC_LvKe { get; set; }
        public string JB_JC_XingHao { get; set; }
        public string JB_JC_BianHao { get; set; }
        public string JB_JC_PeiShu { get; set; }
        public string JB_JC_DanDang { get; set; }
        public string JB_JC_SuDu { get; set; }
        public string JB_JC_GongDian { get; set; }
        public string JB_JC_XinHao { get; set; }
        public string JB_BZ_DunWei { get; set; }
        public string JB_BZ_ShuLiang { get; set; }
        public string JB_BZ_JiChang { get; set; }
        public string JB_BZ_ZhongChe { get; set; }
        public string JB_BZ_KongChe { get; set; }
        public string JB_BZ_LieWei { get; set; }
        public string JB_BZ_WeiXianPin { get; set; }
        public string JB_BZ_ChaoXianChe { get; set; }
        public string JB_GXR_SiJi { get; set; }
        public string JB_GXR_FuSiJi { get; set; }
        public string JB_GXR_YunZhuanCheZhang { get; set; }
        public string JB_GXR_LieCheZhang { get; set; }
        public string JB_GXR_ZhiBanYuan { get; set; }
        public string JB_TianQi { get; set; }
        public string JB_ShiGuXingZhi { get; set; }
        public Nullable<System.DateTime> JB_FS_ShangXing { get; set; }
        public Nullable<System.DateTime> JB_FS_XiaXing { get; set; }
        public Nullable<System.DateTime> JB_FJ_ShangXing { get; set; }
        public Nullable<System.DateTime> JB_FJ_XiaXing { get; set; }
        public Nullable<System.DateTime> JB_KT_ShangXing { get; set; }
        public Nullable<System.DateTime> JB_KT_XiaXing { get; set; }
        public System.DateTime JB_CreatTime { get; set; }
        public System.DateTime JB_UpdateTime { get; set; }
        public Nullable<decimal> JB_ZB_X { get; set; }
        public Nullable<decimal> C__JB_ZB_Y { get; set; }
        public Nullable<decimal> JB_ZB_Z { get; set; }
        public string JB_Ext1 { get; set; }
        public string JB_Ext2 { get; set; }
        public string JB_Ext3 { get; set; }
    }
}
