//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemloginfo
    {
        public int SL_Id { get; set; }
        public int SL_WrId { get; set; }
        public string SL_WrName { get; set; }
        public string SL_Type { get; set; }
        public string SL_Desc { get; set; }
        public System.DateTime SL_CreateTime { get; set; }
        public string SL_Ext1 { get; set; }
        public string SL_Ext2 { get; set; }
        public string SL_Ext3 { get; set; }
    }
}
