
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGDC.Model
{

using System;
    using System.Collections.Generic;
    
public partial class userinfo
{

    public int User_ID { get; set; }

    public string User_No { get; set; }

    public string User_Name { get; set; }

    public string User_Phone { get; set; }

    public string User_Uint { get; set; }

    public string User_Department { get; set; }

    public string User_Pwd { get; set; }

    public string User_Role { get; set; }

    public string User_Status { get; set; }

    public System.DateTime User_CreateTime { get; set; }

    public int User_RoleID { get; set; }

    public string User_Ext1 { get; set; }

    public string User_Ext2 { get; set; }

    public string User_Ext3 { get; set; }

}

}
