//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_shigu
    {
        public int JB_ID { get; set; }
        public string JB_DD_Ju { get; set; }
        public string JB_DD_Xian { get; set; }
        public string JB_DD_XianBie { get; set; }
        public string JB_DD_QiDian { get; set; }
        public string JB_DD_ZhongDian { get; set; }
        public string JB_DD_XingBie { get; set; }
        public string JB_DD_GongLi { get; set; }
        public string JB_DD_MiShu { get; set; }
        public string JB_DD_Sheng { get; set; }
        public string JB_DD_Shi { get; set; }
        public string JB_DD_Qu { get; set; }
        public string JB_DD_DanWei { get; set; }
        public string JB_DD_ChangSuo { get; set; }
        public string JB_LC_CheCi { get; set; }
        public string JB_LC_CheHao { get; set; }
        public string JB_LC_QiDian { get; set; }
        public string JB_LC_ZhongDian { get; set; }
        public string JB_LC_PeiShu { get; set; }
        public string JB_LC_DanDang { get; set; }
        public string JB_LC_LvKe { get; set; }
        public string JB_JC_XingHao { get; set; }
        public string JB_JC_BianHao { get; set; }
        public string JB_JC_PeiShu { get; set; }
        public string JB_JC_DanDang { get; set; }
        public string JB_JC_SuDu { get; set; }
        public string JB_JC_GongDian { get; set; }
        public string JB_JC_XinHao { get; set; }
        public string JB_BZ_DunWei { get; set; }
        public string JB_BZ_ShuLiang { get; set; }
        public string JB_BZ_JiChang { get; set; }
        public string JB_BZ_ZhongChe { get; set; }
        public string JB_BZ_KongChe { get; set; }
        public string JB_BZ_LieWei { get; set; }
        public string JB_BZ_WeiXianPin { get; set; }
        public string JB_BZ_ChaoXianChe { get; set; }
        public string JB_GXR_SiJi { get; set; }
        public string JB_GXR_FuSiJi { get; set; }
        public string JB_GXR_YunZhuanCheZhang { get; set; }
        public string JB_GXR_LieCheZhang { get; set; }
        public string JB_GXR_ZhiBanYuan { get; set; }
        public string JB_TianQi { get; set; }
        public string JB_ShiGuXingZhi { get; set; }
        public Nullable<System.DateTime> JB_FS_ShangXing { get; set; }
        public Nullable<System.DateTime> JB_FS_XiaXing { get; set; }
        public Nullable<System.DateTime> JB_FJ_ShangXing { get; set; }
        public Nullable<System.DateTime> JB_FJ_XiaXing { get; set; }
        public Nullable<System.DateTime> JB_KT_ShangXing { get; set; }
        public Nullable<System.DateTime> JB_KT_XiaXing { get; set; }
        public System.DateTime JB_CreatTime { get; set; }
        public System.DateTime JB_UpdateTime { get; set; }
        public Nullable<decimal> JB_ZB_X { get; set; }
        public Nullable<decimal> JB_ZB_Y { get; set; }
        public Nullable<decimal> JB_ZB_Z { get; set; }
        public string JB_Ext1 { get; set; }
        public string JB_Ext2 { get; set; }
        public string JB_Ext3 { get; set; }
        public Nullable<int> HG_ID { get; set; }
        public string HG_ZD_ShangXing { get; set; }
        public string HG_ZD_XiaXing { get; set; }
        public string HG_DW_ShangXing { get; set; }
        public string HG_DW_XiaXing { get; set; }
        public string HG_TG_DongCheZu { get; set; }
        public string HG_TG_JiChe { get; set; }
        public string HG_TG_KeChe { get; set; }
        public string HG_TG_HuoChe { get; set; }
        public string HG_SS_DongCheZu { get; set; }
        public string HG_SS_JiChe { get; set; }
        public string HG_SS_CheLiang { get; set; }
        public string HG_SS_QiTa { get; set; }
        public string HG_ZhiJieSunShi { get; set; }
        public string HG_XZ_JiDongChe { get; set; }
        public string HG_XZ_FeiJiDongChe { get; set; }
        public string HG_XZ_XingRen { get; set; }
        public string HG_XZ_DaoKouQingKuang { get; set; }
        public string HG_XZ_GongTieBingXing { get; set; }
        public string HG_XZ_FangHuZhaLan { get; set; }
        public string HG_XZ_GongTieLiJiao { get; set; }
        public string HG_XZ_SuDuQuDuan { get; set; }
        public string HG_XZ_QuXianBanJing { get; set; }
        public string HG_XZ_PoDu { get; set; }
        public string HG_SW_XingMing { get; set; }
        public string HG_SW_DanWei { get; set; }
        public string HG_SW_XingBie { get; set; }
        public string HG_SW_NianLing { get; set; }
        public string HG_SW_MinZu { get; set; }
        public string HG_SW_GongZhong { get; set; }
        public string HG_SW_ShangHaiChengDu { get; set; }
        public string HG_SW_RenYuanShuXing { get; set; }
        public string HG_SiW_LuNei { get; set; }
        public string HG_SiW_LuWai { get; set; }
        public string HG_ZS_LuNei { get; set; }
        public string HG_ZS_LuWai { get; set; }
        public string HG_QS_LuNei { get; set; }
        public string HG_QS_LuWai { get; set; }
        public string HG_ShiGuGaiKuang { get; set; }
        public string HG_Ext1 { get; set; }
        public string HG_Ext2 { get; set; }
        public string HG_Ext3 { get; set; }
        public Nullable<int> ZR_ID { get; set; }
        public string ZR_ZeRenDanWei { get; set; }
        public string ZR_ZeRenDanWeiShuXing { get; set; }
        public string ZR_ZeRenBuMen { get; set; }
        public string ZR_ZeRenChengDu { get; set; }
        public string ZR_YuanYinLeiBie { get; set; }
        public string ZR_ShiGuLeiBie { get; set; }
        public string ZR_ShiGuDengJi { get; set; }
        public string ZR_ZhiBanJianCha { get; set; }
        public Nullable<System.DateTime> ZR_TianBaoShiJian { get; set; }
        public string ZR_BaoGaoCiShu { get; set; }
        public string ZR_ShiGuDiaoChaBaoGao { get; set; }
        public string ZR_XianChangDianChaZiLiao { get; set; }
        public string ZR_SunShiJiSuanZiLiao { get; set; }
        public string ZR_ShiGuRenDingShu { get; set; }
        public string ZR_AnJianBaoEr { get; set; }
        public string ZR_QiTa { get; set; }
        public string ZR_TePaiBanDiaoChaBaoGao { get; set; }
        public string ZR_SheDuDiaoChaBaoGao { get; set; }
        public string ZR_Ext1 { get; set; }
        public string ZR_Ext2 { get; set; }
        public string ZR_Ext3 { get; set; }
    }
}
